New Filtering
mlemgroup/MlemMiddleware pull request #17
Opened 2024-06-05 02:21 UTC by EricBAndrews

This PR introduces new filtering logic that unifies both deduping behavior and keyword/read filtering.

The core element is a `FilterProviding`, which is a protocol to which individual filters conform. `FilterProviding` offers `filter`, which filters a list of items and returns the ones that pass, and `reset`, which resets the filter and, if passed a list of items, filters them and returns the ones that pass.

Individual filters are then defined with whatever internal helpers they need; e.g., `PostDedupeFilter` stores a list of seen `URL`s, and is responsible for maintaining that list.

Filters can be composed together into a `MultiFilter`. A `MultiFilter` offers the same `filter` and `reset` methods, but contains a list of `FilterProviding`; `filter` calls these filters in order and returns the values that pass all filters.

Filters can also be activated or deactivated using their `active` property, and the `MultiFilter` exposes methods to activate and deactivate its internal filters.

2024-06-05 12:03 UTC, Sjmarf requested changes
Looks great! A few small comments :)

2024-06-05 12:03 UTC, Sjmarf commented on Sources/MlemMiddleware/FeedLoaders/Filtering/Filters/Post/PostDedupeFilter.swift
> +class PostDedupeFilter: FilterProviding {
I wonder if it would be possible for this to handle other types too? At some point we'll either need an equivalent filter for comments, or it might be possible to have this filter handle both types. Maybe it could be generic, with `FilterTarget` constrained to `ActorIdentifiable`? Or alternatively it could be non-generic and `FilterTarget` could be _equal_ to `ActorIdentifiable` 🤔

2024-06-05 12:03 UTC, Sjmarf commented on Sources/MlemMiddleware/FeedLoaders/Filtering/Filters/Post/PostKeywordFilter.swift
> +    }
nit

```suggestion
    private var keywords: Set<String>
    var active: Bool = true
    
    init(keywords: Set<String>) {
        self.keywords = keywords
    }
```

2024-06-05 12:03 UTC, Sjmarf commented on Sources/MlemMiddleware/FeedLoaders/Filtering/Filterable.swift
> +    associatedtype Filters
I don't think the name "Filters" should be plural. Maybe `FilterType` would be a better name?

2024-06-05 12:03 UTC, Sjmarf commented on Sources/MlemMiddleware/FeedLoaders/Filtering/PostFilter.swift
> +public enum PostFilters {
Similar to the comment above; maybe this would be better named `PostFilterType`? That would match our `PostType` enum better.

2024-06-06 00:39 UTC, EricBAndrews commented on Sources/MlemMiddleware/FeedLoaders/Filtering/Filters/Post/PostDedupeFilter.swift
> +class PostDedupeFilter: FilterProviding {
Non-generic doesn't work because of `MultiFilter` conformance requirements, but generic works a charm

2024-06-07 11:04 UTC, Sjmarf approved these changes
LGTM 👍

2024-06-09 19:56 UTC, merged