Report
mlemgroup/MlemMiddleware pull request #83
Opened 2024-12-17 22:43 UTC by Sjmarf

2024-12-20 02:05 UTC, EricBAndrews requested changes
Looks good! One refactoring note.

2024-12-20 02:05 UTC, EricBAndrews commented on Sources/MlemMiddleware/API Client/ApiClient+Report.swift
> +    func resolveReport(
Do we want to have this broken out into separate functions for each report type? We define the `Report` abstraction as a wrapper on top of the Lemmy API, so it makes more sense to me for the abstraction work to happen in `Report` and keep `ApiClient` dumb and closely mapped to the Lemmy API.

2024-12-21 12:41 UTC, Sjmarf commented on Sources/MlemMiddleware/API Client/ApiClient+Report.swift
> +    func resolveReport(
Sure, that makes sense 👍

2024-12-22 22:24 UTC, EricBAndrews approved these changes
LGTM! 🔥

2024-12-22 22:27 UTC, merged