Move UserStub to Mlem
mlemgroup/MlemMiddleware pull request #9
Opened 2024-05-20 19:43 UTC by Sjmarf

Changes are described in the Mlem PR [here](). I also removed all `SwiftUI` imports in favor of `Observation`, which `SwiftUI` imports.

2024-05-20 20:34 UTC, EricBAndrews requested changes

2024-05-20 20:34 UTC, EricBAndrews commented on Sources/MlemMiddleware/API Client/Caching/Conformance/Community+CacheExtensions.swift
> +        api.contentUpdateCallback(self)
Build fails on this line--is this function defined?

2024-05-20 20:49 UTC, Sjmarf commented on Sources/MlemMiddleware/API Client/Caching/Conformance/Community+CacheExtensions.swift
> +        api.contentUpdateCallback(self)
Oops, that's not meant to be there. Removed 👍

2024-05-21 23:20 UTC, EricBAndrews approved these changes
LGTM 👍

2024-05-22 10:45 UTC, merged